services:
  1browser:
    build: .
    ports:
      - "80:80"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    ports:
      - "5432:5432/tcp"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: 1browser
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  postgres:
