# fly.toml app configuration file generated for 1browser on 2024-09-22T17:44:25+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '1browser'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
